---
xmlrpc:
    interface: 127.0.0.1
    # 5566 is so cool! just kidding
    port: 5566
lexicon:
    # how many gram we want to use in lexicon database
    ngram: 4
# redis arguments goes here
redis:
    host: localhost
    port: 6379
    # password: xxxxx
...
